import React from 'react';

export const Regionchildren = [
    {
        title: "East",
        Childrens: [
            {
                title:"Bihar",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Jharkand",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Odish",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Assam",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Manipur",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Meghalaya",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Mizoram",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Nagaland",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Arunachal Pradesh",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Sikkim",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Tripura",
                Childrens:
                [
                    {
                        title:"vijaypur"
                    }
                ]
            },

        ]
    },
    {
        title: "west",
        Childrens: [
            {
                title:"Goa",
                Childrens:[
                    {
                        title:"bagalkot"
                    }
                ]
            },
            {
                title:"Gujarat",
                Childrens:[
                    {
                        title:"bagalkot"
                    }
                ]
            },
            {
                title:"Maharashtra",
                Childrens:[
                    {
                        title:"bagalkot"
                    }
                ]
            },
            {
                title:"Rajasthan",
                Childrens:[
                    {
                        title:"bagalkot"
                    }
                ]
            },
        ]
    },
    {
        title: "North",
        Childrens: [
            {
                title:"Jammu and Kashmir",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Himachal Pradesh",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Punjab",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Uttarakhand",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Haryana",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Delhi",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Uttar Pradesh",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Rajasthan",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Ladakh",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
        ]
    },
    {
        title: "South",
        Childrens: [
            {
                title:"Karnataka",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Andhra Pradesh",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Kerala",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Tamil Nadu",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
            {
                title:"Telngana",
                Childrens:[
                    {
                        title:"vijaypur"
                    }
                ]
            },
        ]
    },
]


